# Generated by Django 2.0.7 on 2018-08-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='789456', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiek', models.SmallIntegerField(default=20, max_length=2)),
                ('plec', models.CharField(choices=[('M', 'Male'), ('K', 'Kobieta')], default='M', max_length=1)),
                ('wyksztalcenie', models.CharField(choices=[('p', 'Podstawowe'), ('g', 'Gimnazjalne'), ('s', 'Średnie'), ('w', 'Wyższe')], default='p', max_length=1)),
                ('zaAI', models.BooleanField(choices=[(True, 'TAK'), (False, 'NIE')], default=True)),
            ],
        ),
    ]
