# Generated by Django 2.0.7 on 2018-08-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='wiek',
            field=models.SmallIntegerField(default=20),
        ),
    ]
