# Generated by Django 2.0.7 on 2018-08-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20180807_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='plec',
            field=models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], default='M', max_length=1),
        ),
    ]
