# Generated by Django 2.1 on 2018-08-25 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0004_survey_uzytkownik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik', models.BooleanField(choices=[(True, 'TAK'), (False, 'NIE')], default=True)),
                ('czas_oddania', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
